export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  OIDB_REVIEW = 'OIDB_REVIEW',
  FACULTY_ROUTING = 'FACULTY_ROUTING',
  DEPARTMENT_ROUTING = 'DEPARTMENT_ROUTING',
  YGK_EVALUATION = 'YGK_EVALUATION',
  RANKED = 'RANKED',
  FACULTY_BOARD = 'FACULTY_BOARD',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  WAITLISTED = 'WAITLISTED',
}
