export enum DocumentType {
  TRANSCRIPT = 'TRANSCRIPT',
  OSYM_RESULT = 'OSYM_RESULT',
  ENGLISH_PROFICIENCY = 'ENGLISH_PROFICIENCY',
  IDENTITY = 'IDENTITY',
  STUDENT_CERTIFICATE = 'STUDENT_CERTIFICATE',
  COURSE_CONTENTS = 'COURSE_CONTENTS',
  OSYM_PLACEMENT = 'OSYM_PLACEMENT',
  INTIBAK = 'INTIBAK',
  OTHER = 'OTHER',
}
